package com.redspace.findmyhome

object DataProvider {
    val propertyLists = listOf(
        Property(
            id = 1,
            title = "Beautiful house for renting in downtown",
            address = "1234 South Park Street",
            bedrooms = 4,
            bathrooms = 2,
            postDate = 1655496117,
            priceInCad = 3000,
            summary = "New house in Halifax downtown. 4 bedrooms, 2 baths, living room, kitchen, parking for 2 cars, pet friendly, in-suit laundry, 2000 sqft.",
            description = "Why rent an apartment when you can rent a house with everything that an apartment would offer you?\\n\\nYearly Lease. starting from $3,100 monthly for year lease. Whether you're just starting out, have a growing family or enjoying your retirement, we have the ideal home for you!\\n\\nFour bedroom 2 level homes with open concept layouts, elegant kitchens with fine intricate molding details, rich granite countertops, spacious bedrooms, all wood flooring, great workmanship and total confidence in quality. Master bedroom and ensuite located on main floor.\\n\\nIncluded heat, hot water, 6 top of the line stainless steel appliances.\\n\\nPower not included.\\n\\nWired for fibre optic large fenced yard.\\nNo more mortgage, & property taxes and repairs, we'll take care all of that for you.\\nLeases starting May 2022\\nPlease call or email us for availability\\n\\n(902)403-6393\\nPet friendly homes! ( Yes, dogs allowed!)",
            imageId = R.drawable.property1,
            parking = true,
            petFriendly = true,
            agreementType = "1 year",
            moveInDate = 1655496117,
            size = 2000,
            furnished = false,
            smokePermitted = false,
            accessibility = false,
        ),
        Property(
            id = 2,
            title = "Beautiful house for renting in downtown",
            address = "1234 South Park Street",
            bedrooms = 4,
            bathrooms = 2,
            postDate = 1655496117,
            priceInCad = 3000,
            summary = "New house in Halifax downtown. 4 bedrooms, 2 baths, living room, kitchen, parking for 2 cars, pet friendly, in-suit laundry, 2000 sqft.",
            description = "Why rent an apartment when you can rent a house with everything that an apartment would offer you?\\n\\nYearly Lease. starting from $3,100 monthly for year lease. Whether you're just starting out, have a growing family or enjoying your retirement, we have the ideal home for you!\\n\\nFour bedroom 2 level homes with open concept layouts, elegant kitchens with fine intricate molding details, rich granite countertops, spacious bedrooms, all wood flooring, great workmanship and total confidence in quality. Master bedroom and ensuite located on main floor.\\n\\nIncluded heat, hot water, 6 top of the line stainless steel appliances.\\n\\nPower not included.\\n\\nWired for fibre optic large fenced yard.\\nNo more mortgage, & property taxes and repairs, we'll take care all of that for you.\\nLeases starting May 2022\\nPlease call or email us for availability\\n\\n(902)403-6393\\nPet friendly homes! ( Yes, dogs allowed!)",
            imageId = R.drawable.property2,
            parking = true,
            petFriendly = true,
            agreementType = "1 year",
            moveInDate = 1655496117,
            size = 2000,
            furnished = false,
            smokePermitted = false,
            accessibility = false,
        ),
        Property(
            id = 3,
            title = "Beautiful house for renting in downtown",
            address = "1234 South Park Street",
            bedrooms = 4,
            bathrooms = 2,
            postDate = 1655496117,
            priceInCad = 3000,
            summary = "New house in Halifax downtown. 4 bedrooms, 2 baths, living room, kitchen, parking for 2 cars, pet friendly, in-suit laundry, 2000 sqft.",
            description = "Why rent an apartment when you can rent a house with everything that an apartment would offer you?\\n\\nYearly Lease. starting from $3,100 monthly for year lease. Whether you're just starting out, have a growing family or enjoying your retirement, we have the ideal home for you!\\n\\nFour bedroom 2 level homes with open concept layouts, elegant kitchens with fine intricate molding details, rich granite countertops, spacious bedrooms, all wood flooring, great workmanship and total confidence in quality. Master bedroom and ensuite located on main floor.\\n\\nIncluded heat, hot water, 6 top of the line stainless steel appliances.\\n\\nPower not included.\\n\\nWired for fibre optic large fenced yard.\\nNo more mortgage, & property taxes and repairs, we'll take care all of that for you.\\nLeases starting May 2022\\nPlease call or email us for availability\\n\\n(902)403-6393\\nPet friendly homes! ( Yes, dogs allowed!)",
            imageId = R.drawable.property3,
            parking = true,
            petFriendly = true,
            agreementType = "1 year",
            moveInDate = 1655496117,
            size = 2000,
            furnished = false,
            smokePermitted = false,
            accessibility = false,
        ),
    )
}